### ISSUE TITLE
build-action using non-fork zola

### ISSUE THREAD

**Issue by trwbox** [rwtechwiki/oldwiki#52]
Saw you were using my build action, and thought you'd want to know that it was updated to the newest obsidian-zola at the time of writing. 

I was also taking a look, and my action has ppeetteerrs' obsidian-zola hard coded right now, so I don't believe your fork is being used, but I could probably implement using a different repo if you plan on using your fork.

**Comment by pimgit0** [comment]
ahh thatd be great thank you! i presume that's why im not seeing any html changes!

**Comment by trwbox** [comment]
https://github.com/trwbox/obsidian-zola-build-action/releases/tag/v0.1.3.2-testing

You can try this release that should use your own repo after you specify `ZOLA_REPO` in the main.yml.

**Comment by pimgit0** [comment]
I had to replace `deploy` with `build` in the second `uses:` field to get the action to run. Maybe I have the `ZOLA_REPO` field in the wrong place, since we still appear to be getting the original page templates.
![image](https://user-images.githubusercontent.com/55944518/180419953-61a7fb04-ee7e-40ae-9f9a-1f4135ef6f6b.png)

**Comment by trwbox** [comment]
Sorry for the slow response, I didn't seem to get a notification, and just saw this. Yah. That replacement is my bad, I forgot I changed the name of the repo. On line 13 where is says ```trwbox/obsidian-zola-build-action@v0.1.3.1-alpha```. If you replace the `v0.1.3.1-alpha` with ```v0.1.3.2-testing``` it should use the update. The ```ZOLA_REPO``` should be in the right place, so if it still doesn't work, let me know and I'll look into it.

**Comment by pimgit0** [comment]
Ahh thanks for the response. That doesnt seem to have fixed it, and I've tried now with and without `.git` after the repo name.

**Comment by trwbox** [comment]
I think I fixed it? There was an issue with how I was doing a check. You can take a look at my site with it now firing off a JavaScript alert. I also created Pull Request to fix an issue with the workflow YAML too.

[https://obsidian-zola.trwbox.com/docs/home/](https://obsidian-zola.trwbox.com/docs/home/)

**Comment by pimgit0** [comment]
It works! Thanks, I presume the tick marks in the txt were code formatting like on github then.
